"use client";
import { useEffect,useMemo,useState } from "react";

type Category={id:number;name:string;subcategories:{id:number;name:string}[]};
type Source={media:string;original_category:string;original_subcategory:string;ad_count:number;category_id:number|null;subcategory_id:number|null};
type Data={categories:Category[];sources:Source[]};

export function CategorySettings(){
  const [data,setData]=useState<Data>({categories:[],sources:[]}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[media,setMedia]=useState("すべて"),[query,setQuery]=useState(""),[categoryName,setCategoryName]=useState(""),[subName,setSubName]=useState(""),[parent,setParent]=useState("");
  const load=async()=>{setLoading(true);setError("");try{const response=await fetch("/api/admin/categories",{cache:"no-store"}),json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)}catch(e){setError(e instanceof Error?e.message:"取得できませんでした")}finally{setLoading(false)}};
  useEffect(()=>{void (async()=>{try{const response=await fetch("/api/admin/categories",{cache:"no-store"}),json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)}catch(e){setError(e instanceof Error?e.message:"取得できませんでした")}finally{setLoading(false)}})()},[]);
  const save=async(body:object)=>{setLoading(true);setError("");try{const response=await fetch("/api/admin/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),json=await response.json();if(!response.ok)throw new Error(json.error);setData(json);setCategoryName("");setSubName("")}catch(e){setError(e instanceof Error?e.message:"保存できませんでした")}finally{setLoading(false)}};
  const sources=useMemo(()=>data.sources.filter(row=>(media==="すべて"||row.media===media)&&`${row.original_category} ${row.original_subcategory}`.toLowerCase().includes(query.toLowerCase())),[data.sources,media,query]);
  return <>
    {error&&<div className="data-error">{error}<button onClick={load}>再読み込み</button></div>}
    <section className="settings-summary"><div><span>共通カテゴリ</span><strong>{data.categories.length}</strong></div><div><span>小カテゴリ</span><strong>{data.categories.reduce((n,c)=>n+c.subcategories.length,0)}</strong></div><div><span>割り当て対象</span><strong>{data.sources.length}</strong></div><div><span>未割り当て</span><strong>{data.sources.filter(x=>!x.category_id).length}</strong></div></section>
    <div className="settings-grid"><section className="admin-card"><div className="admin-card-title"><div><h2>共通カテゴリを作成</h2><p>分析画面で使うカテゴリと小カテゴリ</p></div></div><form onSubmit={e=>{e.preventDefault();if(categoryName.trim())void save({action:"category",name:categoryName.trim()})}} className="inline-form"><input value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="例：ES"/><button disabled={loading}>追加</button></form><form onSubmit={e=>{e.preventDefault();if(parent&&subName.trim())void save({action:"subcategory",categoryId:Number(parent),name:subName.trim()})}} className="inline-form three"><select value={parent} onChange={e=>setParent(e.target.value)}><option value="">親カテゴリを選択</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input value={subName} onChange={e=>setSubName(e.target.value)} placeholder="例：es"/><button disabled={loading}>追加</button></form><div className="category-tree">{data.categories.map(c=><div key={c.id}><b>{c.name}</b><span>{c.subcategories.length}件</span>{c.subcategories.map(s=><small key={s.id}>{s.name}</small>)}</div>)}</div></section>
    <section className="admin-card mapping-card"><div className="admin-card-title"><div><h2>メディア別カテゴリの割り当て</h2><p>元カテゴリを共通カテゴリ・小カテゴリへ統合</p></div><span>{sources.length}件</span></div><div className="admin-filters"><select value={media} onChange={e=>setMedia(e.target.value)}><option>すべて</option><option>Digmedia</option><option>就活市場</option><option>ベンチャー就活</option></select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="元カテゴリを検索"/></div><div className="mapping-list">{sources.map(row=>{const selected=data.categories.find(c=>c.id===row.category_id);return <div key={`${row.media}-${row.original_category}-${row.original_subcategory}`}><div className="source-name"><span>{row.media}</span><b>{row.original_category}</b><small>{row.original_subcategory||"小カテゴリなし"}・広告 {row.ad_count}件</small></div><select value={row.category_id??""} onChange={e=>void save({action:"mapping",media:row.media,originalCategory:row.original_category,originalSubcategory:row.original_subcategory,categoryId:e.target.value?Number(e.target.value):null,subcategoryId:null})}><option value="">割り当てなし</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select disabled={!selected} value={row.subcategory_id??""} onChange={e=>void save({action:"mapping",media:row.media,originalCategory:row.original_category,originalSubcategory:row.original_subcategory,categoryId:row.category_id,subcategoryId:e.target.value?Number(e.target.value):null})}><option value="">小カテゴリなし</option>{selected?.subcategories.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>})}{!loading&&!sources.length&&<p className="empty-admin">該当するカテゴリはありません</p>}</div></section></div>
  </>;
}
