"use client";
import { useEffect,useMemo,useRef,useState } from "react";
type Category={id:number;name:string};
type Source={media:string;original_category:string;original_subcategory:string;ad_count:number;category_id:number|null};
type Data={categories:Category[];sources:Source[]};
type Selection={media:string;originalCategory:string;originalSubcategory:string};
const mediaNames=["Digmedia","就活市場","ベンチャー就活"];
const keyOf=(item:Selection)=>`${item.media}\u0000${item.originalCategory}\u0000${item.originalSubcategory}`;

export function CategorySettings(){
  const [data,setData]=useState<Data>({categories:[],sources:[]}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[name,setName]=useState(""),[media,setMedia]=useState(""),[sourceKey,setSourceKey]=useState(""),[selections,setSelections]=useState<Selection[]>([]),[editingId,setEditingId]=useState<number|null>(null),[modalOpen,setModalOpen]=useState(false);
  const modalRef=useRef<HTMLDivElement>(null),closeButtonRef=useRef<HTMLButtonElement>(null),previousFocusRef=useRef<HTMLElement|null>(null);
  const reset=()=>{setName("");setMedia("");setSourceKey("");setSelections([]);setEditingId(null);setModalOpen(false)};
  const load=async()=>{setLoading(true);setError("");try{const response=await fetch("/api/admin/categories",{cache:"no-store"}),json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)}catch(e){setError(e instanceof Error?e.message:"取得できませんでした")}finally{setLoading(false)}};
  useEffect(()=>{void (async()=>{try{const response=await fetch("/api/admin/categories",{cache:"no-store"}),json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)}catch(e){setError(e instanceof Error?e.message:"取得できませんでした")}finally{setLoading(false)}})()},[]);
  useEffect(()=>{if(!modalOpen)return;previousFocusRef.current=document.activeElement as HTMLElement|null;closeButtonRef.current?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();reset();return}if(event.key!=="Tab"||!modalRef.current)return;const items=[...modalRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!items.length)return;const first=items[0],last=items.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",onKey);return()=>{document.removeEventListener("keydown",onKey);previousFocusRef.current?.focus()}},[modalOpen]);
  const sourceOptions=useMemo(()=>data.sources.filter(source=>source.media===media&&(source.category_id===null||source.category_id===editingId)&&!selections.some(item=>keyOf(item)===keyOf({media:source.media,originalCategory:source.original_category,originalSubcategory:source.original_subcategory}))),[data.sources,media,selections,editingId]);
  const mappingsFor=(categoryId:number)=>data.sources.filter(source=>source.category_id===categoryId);
  const request=async(body:object)=>{setLoading(true);setError("");try{const response=await fetch("/api/admin/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),json=await response.json();if(!response.ok)throw new Error(json.error);setData(json);reset()}catch(e){setError(e instanceof Error?e.message:"保存できませんでした")}finally{setLoading(false)}};
  const addSelection=()=>{const source=data.sources.find(item=>keyOf({media:item.media,originalCategory:item.original_category,originalSubcategory:item.original_subcategory})===sourceKey);if(!source)return;setSelections(current=>[...current,{media:source.media,originalCategory:source.original_category,originalSubcategory:source.original_subcategory}]);setSourceKey("")};
  const edit=(category:Category)=>{setEditingId(category.id);setName(category.name);setSelections(mappingsFor(category.id).map(source=>({media:source.media,originalCategory:source.original_category,originalSubcategory:source.original_subcategory})));setMedia("");setSourceKey("");setModalOpen(true)};
  const save=()=>{if(!name.trim()){setError("共通カテゴリ名を入力してください");return}if(!selections.length){setError("媒体と小カテゴリを1件以上追加してください");return}void request({action:"save_bundle",categoryId:editingId,name:name.trim(),selections})};
  const remove=()=>{if(editingId&&window.confirm(`「${name}」を削除しますか？`))void request({action:"delete_bundle",categoryId:editingId})};
  return <>{error&&<div className="data-error">{error}<button onClick={load}>再読み込み</button></div>}
    <section className="settings-summary"><div><span>共通カテゴリ</span><strong>{data.categories.length}</strong></div><div><span>登録済みの組み合わせ</span><strong>{data.sources.filter(x=>x.category_id).length}</strong></div><div><span>利用媒体</span><strong>{new Set(data.sources.filter(x=>x.category_id).map(x=>x.media)).size}</strong></div><div><span>未登録の小カテゴリ</span><strong>{data.sources.filter(x=>!x.category_id).length}</strong></div></section>
    <div className="bundle-layout"><section className="admin-card bundle-editor"><div className="admin-card-title"><div><h2>{editingId?"共通カテゴリを編集":"共通カテゴリを登録"}</h2><p>媒体ごとの小カテゴリを一つの名称にまとめます</p></div>{editingId&&<button className="quiet-button" onClick={reset}>新規登録へ戻る</button>}</div><div className="bundle-form"><label><span>① 共通カテゴリの名称</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="例：ES対策"/></label><div className="bundle-step"><span>② 媒体と小カテゴリを選択</span><div><select value={media} onChange={e=>{setMedia(e.target.value);setSourceKey("")}}><option value="">媒体を選択</option>{mediaNames.map(value=><option key={value}>{value}</option>)}</select><select value={sourceKey} onChange={e=>setSourceKey(e.target.value)} disabled={!media}><option value="">小カテゴリを選択</option>{sourceOptions.map(source=>{const value=keyOf({media:source.media,originalCategory:source.original_category,originalSubcategory:source.original_subcategory});return <option key={value} value={value}>{source.original_subcategory||source.original_category}（{source.original_category}・{source.ad_count}件）</option>})}</select><button onClick={addSelection} disabled={!sourceKey}>追加</button></div></div><div className="selected-pairs"><header><b>登録する組み合わせ</b><span>{selections.length}件</span></header>{selections.map((item,index)=><div key={keyOf(item)}><em>{item.media}</em><b>{item.originalSubcategory||item.originalCategory}</b><small>{item.originalCategory}</small><button onClick={()=>setSelections(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}{!selections.length&&<p>媒体と小カテゴリを選択して「追加」を押してください。</p>}</div><div className="bundle-actions">{editingId&&<button className="danger-button" onClick={remove}>削除</button>}<button className="primary-button" onClick={save} disabled={loading}>{loading?"保存中…":editingId?"変更を保存":"共通カテゴリを登録"}</button></div></div></section>
    <section className="admin-card bundle-list"><div className="admin-card-title"><div><h2>登録済みの共通カテゴリ</h2><p>クリックすると内容の確認・編集ができます</p></div><span>{data.categories.length}件</span></div><div className="bundle-cards">{data.categories.map(category=>{const mappings=mappingsFor(category.id);return <button key={category.id} onClick={()=>edit(category)}><div><span>共通カテゴリ</span><h3>{category.name}</h3></div><strong>{mappings.length}組</strong><div className="bundle-media">{mediaNames.map(value=>{const count=mappings.filter(item=>item.media===value).length;return count?<span key={value}>{value}<b>{count}</b></span>:null})}</div><small>クリックして詳細を確認 →</small></button>})}{!loading&&!data.categories.length&&<div className="empty-admin"><b>共通カテゴリはまだありません</b><p>左のフォームから最初の共通カテゴリを登録してください。</p></div>}</div></section></div>
    {editingId&&modalOpen&&<div ref={modalRef} className="bundle-modal" role="dialog" aria-modal="true" aria-label={`${name}の編集`}><button className="modal-backdrop" onClick={reset} aria-label="閉じる"/><div><header><div><span>共通カテゴリの確認・編集</span><h2>{name}</h2></div><button ref={closeButtonRef} onClick={reset} aria-label="編集画面を閉じる">×</button></header><div className="modal-bundle-form"><label><span>共通カテゴリの名称</span><input value={name} onChange={e=>setName(e.target.value)}/></label><div className="bundle-step"><span>媒体と小カテゴリを追加</span><div><select value={media} onChange={e=>{setMedia(e.target.value);setSourceKey("")}}><option value="">媒体を選択</option>{mediaNames.map(value=><option key={value}>{value}</option>)}</select><select value={sourceKey} onChange={e=>setSourceKey(e.target.value)} disabled={!media}><option value="">小カテゴリを選択</option>{sourceOptions.map(source=>{const value=keyOf({media:source.media,originalCategory:source.original_category,originalSubcategory:source.original_subcategory});return <option key={value} value={value}>{source.original_subcategory||source.original_category}（{source.original_category}）</option>})}</select><button onClick={addSelection} disabled={!sourceKey}>追加</button></div></div><div className="selected-pairs">{selections.map((item,index)=><div key={keyOf(item)}><em>{item.media}</em><b>{item.originalSubcategory||item.originalCategory}</b><small>{item.originalCategory}</small><button onClick={()=>setSelections(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div></div><footer><button className="danger-button" onClick={remove}>削除</button><button className="primary-button" onClick={save} disabled={loading}>変更を保存</button></footer></div></div>}
  </>;
}
